=== Krusher-git/XmlTaskEpam/src/test/resources/schema/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/periodicals"
        xmlns:tns="http://www.example.com/periodicals"
        elementFormDefault="qualified">
    <element name="periodical" type="tns:periodical" abstract="true"/>
    <element name="monthly-periodical" type="tns:monthlyPeriodical" substitutionGroup="tns:periodical"/>
    <element name="not-monthly-periodical" type="tns:notMonthlyPeriodical" substitutionGroup="tns:periodical"/>

    <element name="papers">
        <complexType>
            <sequence>
                <element ref="tns:periodical"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="periodical">
        <sequence>
            <element name="title" type="string"/>
            <element name="type" type="tns:typePeriodical"/>
            <element name="chars" type="tns:chars"/>
        </sequence>
        <attribute name="id" type="tns:idPaper" use="required"/>
        <attribute name="source" type="string" use="optional" default="www.google.com"/>
    </complexType>

    <complexType name="monthlyPeriodical">
        <complexContent>
            <extension base="tns:periodical">
                <sequence>
                    <element name="monthly" type="boolean"/>
                    <element name="date" type="date"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="notMonthlyPeriodical">
        <complexContent>
            <extension base="tns:periodical">
                <sequence>
                    <element name="number" type="positiveInteger"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="typePeriodical">
        <restriction base="string">
            <enumeration value="paper"/>
            <enumeration value="magazine"/>
            <enumeration value="booklet"/>
        </restriction>
    </simpleType>

    <complexType name="chars">
        <sequence>
            <element name="color" type="boolean"/>
            <element name="capacity" type="positiveInteger"/>
            <element name="glossy" type="boolean"/>
            <element name="index" type="boolean"/>
        </sequence>
    </complexType>

    <simpleType name="idPaper">
        <restriction base="ID">
            <pattern value="\w{1,9}"/>
        </restriction>
    </simpleType>
</schema>

=== Krusher-git/XmlTaskEpam/src/main/resources/data/periodicals.xml
<?xml version="1.0" encoding="UTF-8"?>
<papers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.com/periodicals"
        xsi:schemaLocation="http://www.example.com/periodicals ../schema/schema.xsd">
    <monthly-periodical id="m1" source="www.Jjj.com">
        <title>Daily Bugle</title>
        <type>paper</type>
        <chars>
            <color>true</color>
            <capacity>50</capacity>
            <glossy>false</glossy>
            <index>true</index>
        </chars>
        <monthly>true</monthly>
        <date>2018-03-12</date>
    </monthly-periodical>
    <monthly-periodical id="m2">
        <title>Paradise</title>
        <type>paper</type>
        <chars>
            <color>false</color>
            <capacity>33</capacity>
            <glossy>false</glossy>
            <index>false</index>
        </chars>
        <monthly>false</monthly>
        <date>2021-02-05</date>
    </monthly-periodical>
    <monthly-periodical id="m3">
        <title>Black Day</title>
        <type>paper</type>
        <chars>
            <color>true</color>
            <capacity>75</capacity>
            <glossy>false</glossy>
            <index>true</index>
        </chars>
        <monthly>true</monthly>
        <date>2020-02-12</date>
    </monthly-periodical>
    <monthly-periodical id="m4" source="www.Green.com">
        <title>Green</title>
        <type>paper</type>
        <chars>
            <color>false</color>
            <capacity>23</capacity>
            <glossy>false</glossy>
            <index>false</index>
        </chars>
        <monthly>false</monthly>
        <date>2020-03-12</date>
    </monthly-periodical>
    <monthly-periodical id="m5">
        <title>Pyramid</title>
        <type>magazine</type>
        <chars>
            <color>false</color>
            <capacity>43</capacity>
            <glossy>true</glossy>
            <index>false</index>
        </chars>
        <monthly>true</monthly>
        <date>2020-07-12</date>
    </monthly-periodical>
    <monthly-periodical id="m6">
        <title>Magazine</title>
        <type>magazine</type>
        <chars>
            <color>false</color>
            <capacity>31</capacity>
            <glossy>true</glossy>
            <index>true</index>
        </chars>
        <monthly>false</monthly>
        <date>2020-07-12</date>
    </monthly-periodical>
    <monthly-periodical id="m7">
        <title>Wall Street Journal</title>
        <type>magazine</type>
        <chars>
            <color>true</color>
            <capacity>53</capacity>
            <glossy>true</glossy>
            <index>true</index>
        </chars>
        <monthly>true</monthly>
        <date>2020-07-12</date>
    </monthly-periodical>
    <monthly-periodical id="m8">
        <title>Science</title>
        <type>magazine</type>
        <chars>
            <color>false</color>
            <capacity>45</capacity>
            <glossy>false</glossy>
            <index>true</index>
        </chars>
        <monthly>true</monthly>
        <date>2020-07-12</date>
    </monthly-periodical>
    <not-monthly-periodical id="nm9">
        <title>Energy</title>
        <type>booklet</type>
        <chars>
            <color>true</color>
            <capacity>5</capacity>
            <glossy>true</glossy>
            <index>false</index>
        </chars>
        <number>25</number>
    </not-monthly-periodical>
    <not-monthly-periodical id="nm10">
        <title>Negative</title>
        <type>booklet</type>
        <chars>
            <color>false</color>
            <capacity>10</capacity>
            <glossy>false</glossy>
            <index>false</index>
        </chars>
        <number>12</number>
    </not-monthly-periodical>
    <not-monthly-periodical id="nm11">
        <title>Evening</title>
        <type>booklet</type>
        <chars>
            <color>true</color>
            <capacity>15</capacity>
            <glossy>true</glossy>
            <index>false</index>
        </chars>
        <number>13</number>
    </not-monthly-periodical>
    <not-monthly-periodical id="nm12">
        <title>Pennsylvania Today</title>
        <type>booklet</type>
        <chars>
            <color>true</color>
            <capacity>25</capacity>
            <glossy>false</glossy>
            <index>false</index>
        </chars>
        <number>16</number>
    </not-monthly-periodical>
    <not-monthly-periodical id="nm13">
        <title>Weekly Bugle</title>
        <type>paper</type>
        <chars>
            <color>true</color>
            <capacity>50</capacity>
            <glossy>false</glossy>
            <index>false</index>
        </chars>
        <number>19</number>
    </not-monthly-periodical>
    <not-monthly-periodical id="nm14">
        <title>Jet</title>
        <type>paper</type>
        <chars>
            <color>false</color>
            <capacity>10</capacity>
            <glossy>false</glossy>
            <index>true</index>
        </chars>
        <number>16</number>
    </not-monthly-periodical>
    <not-monthly-periodical id="nm15">
        <title>Horizon</title>
        <type>paper</type>
        <chars>
            <color>true</color>
            <capacity>20</capacity>
            <glossy>false</glossy>
            <index>true</index>
        </chars>
        <number>14</number>
    </not-monthly-periodical>
    <not-monthly-periodical id="nm16">
        <title>American</title>
        <type>paper</type>
        <chars>
            <color>true</color>
            <capacity>18</capacity>
            <glossy>false</glossy>
            <index>true</index>
        </chars>
        <number>20</number>
    </not-monthly-periodical>
</papers>
